# Generated by Django 5.2.2 on 2025-06-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='constellation',
            field=models.CharField(blank=True, choices=[('aries', '牡羊座'), ('taurus', '金牛座'), ('gemini', '雙子座'), ('cancer', '巨蟹座'), ('leo', '獅子座'), ('virgo', '處女座'), ('libra', '天秤座'), ('scorpio', '天蠍座'), ('sagittarius', '射手座'), ('capricorn', '魔羯座'), ('aquarius', '水瓶座'), ('pisces', '雙魚座')], max_length=20, null=True),
        ),
    ]
