# Generated by Django 5.2.2 on 2025-06-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customer_constellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birthday_md',
            field=models.CharField(blank=True, help_text='格式為 MM-DD，例如 06-16', max_length=5, null=True),
        ),
    ]
