# Generated by Django 5.2.2 on 2025-06-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='detergent_status',
            field=models.CharField(choices=[('y', '用'), ('n', '聽'), ('z', '說')], default='na', max_length=10, verbose_name='濃縮洗碗精'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loc_status',
            field=models.CharField(choices=[('y', '用'), ('n', '聽'), ('z', '說')], default='na', max_length=10, verbose_name='L.O.C.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sa8_status',
            field=models.CharField(choices=[('y', '用'), ('n', '聽'), ('z', '說')], default='na', max_length=10, verbose_name='SA8'),
        ),
    ]
