# Generated by Django 5.2.2 on 2025-06-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_detergent',
            field=models.BooleanField(default=False, verbose_name='濃縮洗碗精'),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_loc',
            field=models.BooleanField(default=False, verbose_name='L.O.C.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_sa8',
            field=models.BooleanField(default=False, verbose_name='SA8'),
        ),
    ]
