# Generated by Django 5.2.2 on 2025-06-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_customer_has_detergent_customer_has_loc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='has_detergent',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='has_loc',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='has_sa8',
        ),
        migrations.AddField(
            model_name='customer',
            name='detergent_status',
            field=models.CharField(choices=[('yes', '✔ 有'), ('no', '✘ 無'), ('na', '— 不適用')], default='na', max_length=10, verbose_name='濃縮洗碗精'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loc_status',
            field=models.CharField(choices=[('yes', '✔ 有'), ('no', '✘ 無'), ('na', '— 不適用')], default='na', max_length=10, verbose_name='L.O.C.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sa8_status',
            field=models.CharField(choices=[('yes', '✔ 有'), ('no', '✘ 無'), ('na', '— 不適用')], default='na', max_length=10, verbose_name='SA8'),
        ),
    ]
