# Generated by Django 5.2.2 on 2025-06-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_customer_has_detergent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='detergent_status',
            field=models.CharField(choices=[('y', '用'), ('n', '聽'), ('z', '說'), ('na', '無')], default='na', max_length=10, verbose_name='濃縮洗碗精'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='loc_status',
            field=models.CharField(choices=[('y', '用'), ('n', '聽'), ('z', '說'), ('na', '無')], default='na', max_length=10, verbose_name='L.O.C.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sa8_status',
            field=models.CharField(choices=[('y', '用'), ('n', '聽'), ('z', '說'), ('na', '無')], default='na', max_length=10, verbose_name='SA8'),
        ),
    ]
