# Generated by Django 5.2.2 on 2025-06-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_customer_detergent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='espring_status',
            field=models.CharField(choices=[('y', '用'), ('n', '聽'), ('z', '說'), ('na', '無')], default='na', max_length=10, verbose_name='淨水器'),
        ),
    ]
