# Generated by Django 5.2.2 on 2025-06-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_customer_espring_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sky_status',
            field=models.CharField(choices=[('y', '用'), ('n', '聽'), ('z', '說'), ('na', '無')], default='na', max_length=10, verbose_name='空氣清淨機'),
        ),
    ]
