# Generated by Django 5.2.2 on 2025-06-10 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_customer_sky_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='detergent_status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='espring_status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='loc_status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sa8_status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sky_status',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('y', '用'), ('n', '聽'), ('z', '說'), ('na', '無')], max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.product')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
