# Generated by Django 5.2.2 on 2025-06-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_productcategory_remove_customer_detergent_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatusOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='customerproductstatus',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customerproductstatus',
            name='status_options',
            field=models.ManyToManyField(blank=True, to='crm.productstatusoption'),
        ),
        migrations.RemoveField(
            model_name='customerproductstatus',
            name='status',
        ),
    ]
