version: '3.8'

services:
  
  web:
    build: .
    container_name: crm-web
    command: python manage.py runserver 0.0.0.0:8003
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8003:8003"
