# Generated by Django 5.2.1 on 2025-06-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_foodimage_options_foodimage_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
                ('body_fat', models.FloatField()),
                ('visceral_fat', models.FloatField()),
                ('muscle_rate', models.FloatField()),
                ('bmi', models.FloatField()),
                ('bmr', models.FloatField()),
                ('body_age', models.IntegerField()),
            ],
        ),
    ]
