# Generated by Django 5.2.2 on 2025-06-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_weightrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='foodimage',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='foodimage',
            name='image',
            field=models.ImageField(upload_to='uploads/food/'),
        ),
    ]
